server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:h2:mem:wigellbloggdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/WigellBlogg"

app:
  security:
    client-id: "blogg-api"